# Generated by Django 3.2 on 2024-01-19 10:24

import django.contrib.auth.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240119_1706'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='reviews_review_unique_review',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='Недопустимый символ!', regex='^[\\w.@+-]+\\Z'), reviews.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
