# Generated by Django 3.2 on 2024-01-19 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='Введите оценку от 1 до 10.', validators=[django.core.validators.MinValueValidator(1, message='Нельзя ставить оценку ниже 1.'), django.core.validators.MaxValueValidator(10, message='Нельзя ставить оценку выше 10.')], verbose_name='Оценка'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='reviews_review_unique_review'),
        ),
    ]
