# Generated by Django 3.2 on 2024-01-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240118_1648'),
        ('reviews', '0007_auto_20240119_1735'),
    ]

    operations = [
    ]
